name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Increase yarn network timeout
        run: |
          yarn config set network-timeout 300000

      - name: yarn install
        run: |
          yarn install

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          LICENSE_ID: ${{ secrets.LICENSE_ID }}
        run: |
          yarn package-ci
          yarn lint
          yarn tsc

# Failing because virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
